import { ForecastWeatherResponse } from '@weather/contracts';

export const mockForecastWeatherWithoutAQIAndAlertsResponse: ForecastWeatherResponse =
  {
    location: {
      name: 'Budapest Ferenc Liszt International Airport',
      region: 'Budapest',
      country: 'Hungary',
      lat: 47.4297981262207,
      lon: 19.261100769043,
      tz_id: 'Europe/Budapest',
      localtime_epoch: 1759387736,
      localtime: '2025-10-02 08:48',
    },
    current: {
      last_updated_epoch: 1759387500,
      last_updated: '2025-10-02 08:45',
      temp_c: 7.3,
      temp_f: 45.1,
      is_day: 1,
      condition: {
        text: 'Napos idő',
        icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
        code: 1000,
      },
      wind_mph: 13.6,
      wind_kph: 22,
      wind_degree: 37,
      wind_dir: 'NE',
      pressure_mb: 1024,
      pressure_in: 30.24,
      precip_mm: 0,
      precip_in: 0,
      humidity: 66,
      cloud: 0,
      feelslike_c: 3.8,
      feelslike_f: 38.8,
      windchill_c: 5.5,
      windchill_f: 41.8,
      heatindex_c: 8.6,
      heatindex_f: 47.5,
      dewpoint_c: -4.8,
      dewpoint_f: 23.4,
      vis_km: 10,
      vis_miles: 6,
      uv: 0.2,
      gust_mph: 17.1,
      gust_kph: 27.5,
    },
    forecast: {
      forecastday: [
        {
          date: '2025-10-02',
          date_epoch: 1759363200,
          day: {
            maxtemp_c: 13.6,
            maxtemp_f: 56.4,
            mintemp_c: 7.3,
            mintemp_f: 45.1,
            avgtemp_c: 9.9,
            avgtemp_f: 49.8,
            maxwind_mph: 13.6,
            maxwind_kph: 22,
            totalprecip_mm: 0,
            totalprecip_in: 0,
            totalsnow_cm: 0,
            avgvis_km: 10,
            avgvis_miles: 6,
            avghumidity: 39,
            daily_will_it_rain: 0,
            daily_chance_of_rain: 0,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: 'Részben felhős',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            uv: 0.7,
          },
          astro: {
            sunrise: '06:44 AM',
            sunset: '06:20 PM',
            moonrise: '04:29 PM',
            moonset: '12:23 AM',
            moon_phase: 'Waxing Gibbous',
            moon_illumination: 70,
            is_moon_up: 1,
            is_sun_up: 0,
          },
          hour: [
            {
              time_epoch: 1759356000,
              time: '2025-10-02 00:00',
              temp_c: 8.2,
              temp_f: 46.7,
              is_day: 0,
              condition: {
                text: 'Részben felhős',
                icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
                code: 1003,
              },
              wind_mph: 7.8,
              wind_kph: 12.6,
              wind_degree: 24,
              wind_dir: 'NNE',
              pressure_mb: 1025,
              pressure_in: 30.27,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 58,
              cloud: 44,
              feelslike_c: 6,
              feelslike_f: 42.8,
              windchill_c: 6,
              windchill_f: 42.8,
              heatindex_c: 8.2,
              heatindex_f: 46.7,
              dewpoint_c: 0.4,
              dewpoint_f: 32.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 12.5,
              gust_kph: 20.2,
              uv: 0,
            },
            {
              time_epoch: 1759359600,
              time: '2025-10-02 01:00',
              temp_c: 7.7,
              temp_f: 45.9,
              is_day: 0,
              condition: {
                text: 'Részben felhős',
                icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
                code: 1003,
              },
              wind_mph: 7.4,
              wind_kph: 11.9,
              wind_degree: 14,
              wind_dir: 'NNE',
              pressure_mb: 1025,
              pressure_in: 30.27,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 56,
              cloud: 33,
              feelslike_c: 5.6,
              feelslike_f: 42,
              windchill_c: 5.6,
              windchill_f: 42,
              heatindex_c: 7.7,
              heatindex_f: 45.9,
              dewpoint_c: -0.4,
              dewpoint_f: 31.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 12.1,
              gust_kph: 19.4,
              uv: 0,
            },
            {
              time_epoch: 1759363200,
              time: '2025-10-02 02:00',
              temp_c: 7.5,
              temp_f: 45.4,
              is_day: 0,
              condition: {
                text: 'Felhőtlen',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 6.5,
              wind_kph: 10.4,
              wind_degree: 13,
              wind_dir: 'NNE',
              pressure_mb: 1025,
              pressure_in: 30.27,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 54,
              cloud: 14,
              feelslike_c: 5.5,
              feelslike_f: 41.9,
              windchill_c: 5.5,
              windchill_f: 41.9,
              heatindex_c: 7.5,
              heatindex_f: 45.4,
              dewpoint_c: -1.3,
              dewpoint_f: 29.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 10.6,
              gust_kph: 17,
              uv: 0,
            },
            {
              time_epoch: 1759366800,
              time: '2025-10-02 03:00',
              temp_c: 7.4,
              temp_f: 45.4,
              is_day: 0,
              condition: {
                text: 'Felhős',
                icon: '//cdn.weatherapi.com/weather/64x64/night/119.png',
                code: 1006,
              },
              wind_mph: 6,
              wind_kph: 9.7,
              wind_degree: 22,
              wind_dir: 'NNE',
              pressure_mb: 1025,
              pressure_in: 30.26,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 49,
              cloud: 77,
              feelslike_c: 5.6,
              feelslike_f: 42.1,
              windchill_c: 5.6,
              windchill_f: 42.1,
              heatindex_c: 7.4,
              heatindex_f: 45.4,
              dewpoint_c: -2.5,
              dewpoint_f: 27.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 9.8,
              gust_kph: 15.7,
              uv: 0,
            },
            {
              time_epoch: 1759370400,
              time: '2025-10-02 04:00',
              temp_c: 7.5,
              temp_f: 45.5,
              is_day: 0,
              condition: {
                text: 'Felhős',
                icon: '//cdn.weatherapi.com/weather/64x64/night/119.png',
                code: 1006,
              },
              wind_mph: 6.9,
              wind_kph: 11.2,
              wind_degree: 32,
              wind_dir: 'NNE',
              pressure_mb: 1024,
              pressure_in: 30.25,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 45,
              cloud: 75,
              feelslike_c: 5.4,
              feelslike_f: 41.8,
              windchill_c: 5.4,
              windchill_f: 41.8,
              heatindex_c: 7.5,
              heatindex_f: 45.5,
              dewpoint_c: -3.7,
              dewpoint_f: 25.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 10.8,
              gust_kph: 17.4,
              uv: 0,
            },
            {
              time_epoch: 1759374000,
              time: '2025-10-02 05:00',
              temp_c: 7.5,
              temp_f: 45.5,
              is_day: 0,
              condition: {
                text: 'Felhős',
                icon: '//cdn.weatherapi.com/weather/64x64/night/119.png',
                code: 1006,
              },
              wind_mph: 7.4,
              wind_kph: 11.9,
              wind_degree: 37,
              wind_dir: 'NE',
              pressure_mb: 1024,
              pressure_in: 30.25,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 41,
              cloud: 64,
              feelslike_c: 5.3,
              feelslike_f: 41.6,
              windchill_c: 5.3,
              windchill_f: 41.6,
              heatindex_c: 7.5,
              heatindex_f: 45.5,
              dewpoint_c: -4.8,
              dewpoint_f: 23.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 11.2,
              gust_kph: 18,
              uv: 0,
            },
            {
              time_epoch: 1759377600,
              time: '2025-10-02 06:00',
              temp_c: 7.3,
              temp_f: 45.1,
              is_day: 0,
              condition: {
                text: 'Felhőtlen',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 8.5,
              wind_kph: 13.7,
              wind_degree: 37,
              wind_dir: 'NE',
              pressure_mb: 1025,
              pressure_in: 30.26,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 39,
              cloud: 14,
              feelslike_c: 4.7,
              feelslike_f: 40.5,
              windchill_c: 4.7,
              windchill_f: 40.5,
              heatindex_c: 7.3,
              heatindex_f: 45.1,
              dewpoint_c: -5.6,
              dewpoint_f: 22,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 12.8,
              gust_kph: 20.7,
              uv: 0,
            },
            {
              time_epoch: 1759381200,
              time: '2025-10-02 07:00',
              temp_c: 7.5,
              temp_f: 45.5,
              is_day: 1,
              condition: {
                text: 'Napos idő',
                icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                code: 1000,
              },
              wind_mph: 10.1,
              wind_kph: 16.2,
              wind_degree: 39,
              wind_dir: 'NE',
              pressure_mb: 1025,
              pressure_in: 30.27,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 39,
              cloud: 7,
              feelslike_c: 4.7,
              feelslike_f: 40.4,
              windchill_c: 4.7,
              windchill_f: 40.4,
              heatindex_c: 7.5,
              heatindex_f: 45.5,
              dewpoint_c: -5.6,
              dewpoint_f: 21.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.2,
              gust_kph: 22.9,
              uv: 0,
            },
            {
              time_epoch: 1759384800,
              time: '2025-10-02 08:00',
              temp_c: 7.3,
              temp_f: 45.1,
              is_day: 1,
              condition: {
                text: 'Napos idő',
                icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                code: 1000,
              },
              wind_mph: 13.6,
              wind_kph: 22,
              wind_degree: 37,
              wind_dir: 'NE',
              pressure_mb: 1024,
              pressure_in: 30.24,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 66,
              cloud: 0,
              feelslike_c: 5.5,
              feelslike_f: 41.8,
              windchill_c: 5.5,
              windchill_f: 41.8,
              heatindex_c: 8.6,
              heatindex_f: 47.5,
              dewpoint_c: -4.8,
              dewpoint_f: 23.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 17.1,
              gust_kph: 27.5,
              uv: 0.2,
            },
            {
              time_epoch: 1759388400,
              time: '2025-10-02 09:00',
              temp_c: 9.6,
              temp_f: 49.3,
              is_day: 1,
              condition: {
                text: 'Napos idő',
                icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                code: 1000,
              },
              wind_mph: 13.6,
              wind_kph: 22,
              wind_degree: 28,
              wind_dir: 'NNE',
              pressure_mb: 1025,
              pressure_in: 30.28,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 40,
              cloud: 15,
              feelslike_c: 6.7,
              feelslike_f: 44.1,
              windchill_c: 6.7,
              windchill_f: 44.1,
              heatindex_c: 9.6,
              heatindex_f: 49.4,
              dewpoint_c: -3.4,
              dewpoint_f: 25.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 15.7,
              gust_kph: 25.3,
              uv: 0.7,
            },
            {
              time_epoch: 1759392000,
              time: '2025-10-02 10:00',
              temp_c: 10.7,
              temp_f: 51.3,
              is_day: 1,
              condition: {
                text: 'Napos idő',
                icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                code: 1000,
              },
              wind_mph: 13.2,
              wind_kph: 21.2,
              wind_degree: 35,
              wind_dir: 'NE',
              pressure_mb: 1025,
              pressure_in: 30.27,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 38,
              cloud: 20,
              feelslike_c: 8.2,
              feelslike_f: 46.7,
              windchill_c: 8.2,
              windchill_f: 46.7,
              heatindex_c: 10.7,
              heatindex_f: 51.3,
              dewpoint_c: -2.9,
              dewpoint_f: 26.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 15.2,
              gust_kph: 24.4,
              uv: 1.5,
            },
            {
              time_epoch: 1759395600,
              time: '2025-10-02 11:00',
              temp_c: 11.7,
              temp_f: 53.1,
              is_day: 1,
              condition: {
                text: 'Részben felhős',
                icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                code: 1003,
              },
              wind_mph: 12.8,
              wind_kph: 20.5,
              wind_degree: 37,
              wind_dir: 'NE',
              pressure_mb: 1025,
              pressure_in: 30.26,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 37,
              cloud: 54,
              feelslike_c: 9.5,
              feelslike_f: 49.1,
              windchill_c: 9.5,
              windchill_f: 49.1,
              heatindex_c: 11.7,
              heatindex_f: 53.1,
              dewpoint_c: -2.6,
              dewpoint_f: 27.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.7,
              gust_kph: 23.6,
              uv: 2.4,
            },
            {
              time_epoch: 1759399200,
              time: '2025-10-02 12:00',
              temp_c: 12.5,
              temp_f: 54.6,
              is_day: 1,
              condition: {
                text: 'Borús',
                icon: '//cdn.weatherapi.com/weather/64x64/day/122.png',
                code: 1009,
              },
              wind_mph: 12.5,
              wind_kph: 20.2,
              wind_degree: 35,
              wind_dir: 'NE',
              pressure_mb: 1024,
              pressure_in: 30.24,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 34,
              cloud: 94,
              feelslike_c: 10.6,
              feelslike_f: 51,
              windchill_c: 10.6,
              windchill_f: 51,
              heatindex_c: 12.5,
              heatindex_f: 54.6,
              dewpoint_c: -2.7,
              dewpoint_f: 27.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.4,
              gust_kph: 23.2,
              uv: 3,
            },
            {
              time_epoch: 1759402800,
              time: '2025-10-02 13:00',
              temp_c: 13.1,
              temp_f: 55.5,
              is_day: 1,
              condition: {
                text: 'Részben felhős',
                icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                code: 1003,
              },
              wind_mph: 12.3,
              wind_kph: 19.8,
              wind_degree: 30,
              wind_dir: 'NNE',
              pressure_mb: 1023,
              pressure_in: 30.22,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 32,
              cloud: 44,
              feelslike_c: 11.2,
              feelslike_f: 52.2,
              windchill_c: 11.2,
              windchill_f: 52.2,
              heatindex_c: 13.1,
              heatindex_f: 55.5,
              dewpoint_c: -3.2,
              dewpoint_f: 26.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.2,
              gust_kph: 22.8,
              uv: 3.2,
            },
            {
              time_epoch: 1759406400,
              time: '2025-10-02 14:00',
              temp_c: 13.6,
              temp_f: 56.4,
              is_day: 1,
              condition: {
                text: 'Részben felhős',
                icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                code: 1003,
              },
              wind_mph: 12.3,
              wind_kph: 19.8,
              wind_degree: 32,
              wind_dir: 'NNE',
              pressure_mb: 1023,
              pressure_in: 30.21,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 30,
              cloud: 30,
              feelslike_c: 11.9,
              feelslike_f: 53.4,
              windchill_c: 11.9,
              windchill_f: 53.4,
              heatindex_c: 13.6,
              heatindex_f: 56.4,
              dewpoint_c: -3.5,
              dewpoint_f: 25.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.2,
              gust_kph: 22.8,
              uv: 2.6,
            },
            {
              time_epoch: 1759410000,
              time: '2025-10-02 15:00',
              temp_c: 13.5,
              temp_f: 56.4,
              is_day: 1,
              condition: {
                text: 'Napos idő',
                icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                code: 1000,
              },
              wind_mph: 12.5,
              wind_kph: 20.2,
              wind_degree: 35,
              wind_dir: 'NE',
              pressure_mb: 1023,
              pressure_in: 30.2,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 30,
              cloud: 25,
              feelslike_c: 11.8,
              feelslike_f: 53.3,
              windchill_c: 11.8,
              windchill_f: 53.3,
              heatindex_c: 13.6,
              heatindex_f: 56.4,
              dewpoint_c: -3.8,
              dewpoint_f: 25.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 15,
              gust_kph: 24.1,
              uv: 1.8,
            },
            {
              time_epoch: 1759413600,
              time: '2025-10-02 16:00',
              temp_c: 13.3,
              temp_f: 56,
              is_day: 1,
              condition: {
                text: 'Napos idő',
                icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                code: 1000,
              },
              wind_mph: 11.6,
              wind_kph: 18.7,
              wind_degree: 40,
              wind_dir: 'NE',
              pressure_mb: 1022,
              pressure_in: 30.19,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 30,
              cloud: 22,
              feelslike_c: 11.7,
              feelslike_f: 53,
              windchill_c: 11.7,
              windchill_f: 53,
              heatindex_c: 13.3,
              heatindex_f: 56,
              dewpoint_c: -4,
              dewpoint_f: 24.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.7,
              gust_kph: 23.7,
              uv: 0.9,
            },
            {
              time_epoch: 1759417200,
              time: '2025-10-02 17:00',
              temp_c: 12.3,
              temp_f: 54.2,
              is_day: 1,
              condition: {
                text: 'Napos idő',
                icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                code: 1000,
              },
              wind_mph: 9.4,
              wind_kph: 15.1,
              wind_degree: 52,
              wind_dir: 'NE',
              pressure_mb: 1023,
              pressure_in: 30.2,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 31,
              cloud: 16,
              feelslike_c: 10.8,
              feelslike_f: 51.4,
              windchill_c: 10.8,
              windchill_f: 51.4,
              heatindex_c: 12.3,
              heatindex_f: 54.2,
              dewpoint_c: -4.1,
              dewpoint_f: 24.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 13.4,
              gust_kph: 21.5,
              uv: 0.3,
            },
            {
              time_epoch: 1759420800,
              time: '2025-10-02 18:00',
              temp_c: 11.1,
              temp_f: 51.9,
              is_day: 1,
              condition: {
                text: 'Napos idő',
                icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                code: 1000,
              },
              wind_mph: 8.9,
              wind_kph: 14.4,
              wind_degree: 56,
              wind_dir: 'ENE',
              pressure_mb: 1023,
              pressure_in: 30.22,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 34,
              cloud: 16,
              feelslike_c: 9.3,
              feelslike_f: 48.7,
              windchill_c: 9.3,
              windchill_f: 48.7,
              heatindex_c: 11.1,
              heatindex_f: 51.9,
              dewpoint_c: -4.1,
              dewpoint_f: 24.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 13.5,
              gust_kph: 21.8,
              uv: 0,
            },
            {
              time_epoch: 1759424400,
              time: '2025-10-02 19:00',
              temp_c: 10.3,
              temp_f: 50.5,
              is_day: 0,
              condition: {
                text: 'Felhőtlen',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 9.6,
              wind_kph: 15.5,
              wind_degree: 48,
              wind_dir: 'NE',
              pressure_mb: 1024,
              pressure_in: 30.23,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 36,
              cloud: 12,
              feelslike_c: 8.2,
              feelslike_f: 46.7,
              windchill_c: 8.2,
              windchill_f: 46.7,
              heatindex_c: 10.3,
              heatindex_f: 50.5,
              dewpoint_c: -4,
              dewpoint_f: 24.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.6,
              gust_kph: 23.5,
              uv: 0,
            },
            {
              time_epoch: 1759428000,
              time: '2025-10-02 20:00',
              temp_c: 9.7,
              temp_f: 49.4,
              is_day: 0,
              condition: {
                text: 'Felhőtlen',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 9.4,
              wind_kph: 15.1,
              wind_degree: 45,
              wind_dir: 'NE',
              pressure_mb: 1024,
              pressure_in: 30.25,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 38,
              cloud: 8,
              feelslike_c: 7.5,
              feelslike_f: 45.5,
              windchill_c: 7.5,
              windchill_f: 45.5,
              heatindex_c: 9.7,
              heatindex_f: 49.4,
              dewpoint_c: -4,
              dewpoint_f: 24.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.1,
              gust_kph: 22.8,
              uv: 0,
            },
            {
              time_epoch: 1759431600,
              time: '2025-10-02 21:00',
              temp_c: 9.3,
              temp_f: 48.7,
              is_day: 0,
              condition: {
                text: 'Felhőtlen',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 9.4,
              wind_kph: 15.1,
              wind_degree: 45,
              wind_dir: 'NE',
              pressure_mb: 1024,
              pressure_in: 30.25,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 38,
              cloud: 14,
              feelslike_c: 7,
              feelslike_f: 44.6,
              windchill_c: 7,
              windchill_f: 44.6,
              heatindex_c: 9.3,
              heatindex_f: 48.7,
              dewpoint_c: -4.2,
              dewpoint_f: 24.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.1,
              gust_kph: 22.7,
              uv: 0,
            },
            {
              time_epoch: 1759435200,
              time: '2025-10-02 22:00',
              temp_c: 8.9,
              temp_f: 48,
              is_day: 0,
              condition: {
                text: 'Felhőtlen',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 9.6,
              wind_kph: 15.5,
              wind_degree: 42,
              wind_dir: 'NE',
              pressure_mb: 1024,
              pressure_in: 30.25,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 38,
              cloud: 9,
              feelslike_c: 6.5,
              feelslike_f: 43.7,
              windchill_c: 6.5,
              windchill_f: 43.7,
              heatindex_c: 8.9,
              heatindex_f: 48,
              dewpoint_c: -4.5,
              dewpoint_f: 23.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.7,
              gust_kph: 23.6,
              uv: 0,
            },
            {
              time_epoch: 1759438800,
              time: '2025-10-02 23:00',
              temp_c: 8.4,
              temp_f: 47.2,
              is_day: 0,
              condition: {
                text: 'Felhőtlen',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 9.8,
              wind_kph: 15.8,
              wind_degree: 35,
              wind_dir: 'NE',
              pressure_mb: 1024,
              pressure_in: 30.24,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 39,
              cloud: 7,
              feelslike_c: 5.9,
              feelslike_f: 42.6,
              windchill_c: 5.9,
              windchill_f: 42.6,
              heatindex_c: 8.4,
              heatindex_f: 47.2,
              dewpoint_c: -4.7,
              dewpoint_f: 23.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 15.2,
              gust_kph: 24.4,
              uv: 0,
            },
          ],
        },
      ],
    },
  };

export const mockForecastWeatherWithAQIAndAlertsResponse: ForecastWeatherResponse =
  {
    location: {
      name: 'Budapest Ferenc Liszt International Airport',
      region: 'Budapest',
      country: 'Hungary',
      lat: 47.4297981262207,
      lon: 19.261100769043,
      tz_id: 'Europe/Budapest',
      localtime_epoch: 1759388730,
      localtime: '2025-10-02 09:05',
    },
    current: {
      last_updated_epoch: 1759388400,
      last_updated: '2025-10-02 09:00',
      temp_c: 8.2,
      temp_f: 46.8,
      is_day: 1,
      condition: {
        text: 'Napos idő',
        icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
        code: 1000,
      },
      wind_mph: 13.6,
      wind_kph: 22,
      wind_degree: 28,
      wind_dir: 'NNE',
      pressure_mb: 1024,
      pressure_in: 30.24,
      precip_mm: 0,
      precip_in: 0,
      humidity: 57,
      cloud: 0,
      feelslike_c: 4.9,
      feelslike_f: 40.8,
      windchill_c: 6.7,
      windchill_f: 44.1,
      heatindex_c: 9.6,
      heatindex_f: 49.4,
      dewpoint_c: -3.4,
      dewpoint_f: 25.9,
      vis_km: 10,
      vis_miles: 6,
      uv: 0.7,
      gust_mph: 15.7,
      gust_kph: 25.3,
      air_quality: {
        co: 171.85,
        no2: 16.35,
        o3: 27,
        so2: 2.15,
        pm2_5: 10.15,
        pm10: 11.75,
        'us-epa-index': 1,
        'gb-defra-index': 1,
      },
    },
    forecast: {
      forecastday: [
        {
          date: '2025-10-02',
          date_epoch: 1759363200,
          day: {
            maxtemp_c: 13.6,
            maxtemp_f: 56.4,
            mintemp_c: 7.3,
            mintemp_f: 45.1,
            avgtemp_c: 9.9,
            avgtemp_f: 49.8,
            maxwind_mph: 13.6,
            maxwind_kph: 22,
            totalprecip_mm: 0,
            totalprecip_in: 0,
            totalsnow_cm: 0,
            avgvis_km: 10,
            avgvis_miles: 6,
            avghumidity: 39,
            daily_will_it_rain: 0,
            daily_chance_of_rain: 0,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: 'Részben felhős',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            uv: 0.7,
          },
          astro: {
            sunrise: '06:44 AM',
            sunset: '06:20 PM',
            moonrise: '04:29 PM',
            moonset: '12:23 AM',
            moon_phase: 'Waxing Gibbous',
            moon_illumination: 70,
            is_moon_up: 1,
            is_sun_up: 0,
          },
          hour: [
            {
              time_epoch: 1759356000,
              time: '2025-10-02 00:00',
              temp_c: 8.2,
              temp_f: 46.7,
              is_day: 0,
              condition: {
                text: 'Részben felhős',
                icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
                code: 1003,
              },
              wind_mph: 7.8,
              wind_kph: 12.6,
              wind_degree: 24,
              wind_dir: 'NNE',
              pressure_mb: 1025,
              pressure_in: 30.27,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 58,
              cloud: 44,
              feelslike_c: 6,
              feelslike_f: 42.8,
              windchill_c: 6,
              windchill_f: 42.8,
              heatindex_c: 8.2,
              heatindex_f: 46.7,
              dewpoint_c: 0.4,
              dewpoint_f: 32.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 12.5,
              gust_kph: 20.2,
              uv: 0,
            },
            {
              time_epoch: 1759359600,
              time: '2025-10-02 01:00',
              temp_c: 7.7,
              temp_f: 45.9,
              is_day: 0,
              condition: {
                text: 'Részben felhős',
                icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
                code: 1003,
              },
              wind_mph: 7.4,
              wind_kph: 11.9,
              wind_degree: 14,
              wind_dir: 'NNE',
              pressure_mb: 1025,
              pressure_in: 30.27,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 56,
              cloud: 33,
              feelslike_c: 5.6,
              feelslike_f: 42,
              windchill_c: 5.6,
              windchill_f: 42,
              heatindex_c: 7.7,
              heatindex_f: 45.9,
              dewpoint_c: -0.4,
              dewpoint_f: 31.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 12.1,
              gust_kph: 19.4,
              uv: 0,
            },
            {
              time_epoch: 1759363200,
              time: '2025-10-02 02:00',
              temp_c: 7.5,
              temp_f: 45.4,
              is_day: 0,
              condition: {
                text: 'Felhőtlen',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 6.5,
              wind_kph: 10.4,
              wind_degree: 13,
              wind_dir: 'NNE',
              pressure_mb: 1025,
              pressure_in: 30.27,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 54,
              cloud: 14,
              feelslike_c: 5.5,
              feelslike_f: 41.9,
              windchill_c: 5.5,
              windchill_f: 41.9,
              heatindex_c: 7.5,
              heatindex_f: 45.4,
              dewpoint_c: -1.3,
              dewpoint_f: 29.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 10.6,
              gust_kph: 17,
              uv: 0,
            },
            {
              time_epoch: 1759366800,
              time: '2025-10-02 03:00',
              temp_c: 7.4,
              temp_f: 45.4,
              is_day: 0,
              condition: {
                text: 'Felhős',
                icon: '//cdn.weatherapi.com/weather/64x64/night/119.png',
                code: 1006,
              },
              wind_mph: 6,
              wind_kph: 9.7,
              wind_degree: 22,
              wind_dir: 'NNE',
              pressure_mb: 1025,
              pressure_in: 30.26,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 49,
              cloud: 77,
              feelslike_c: 5.6,
              feelslike_f: 42.1,
              windchill_c: 5.6,
              windchill_f: 42.1,
              heatindex_c: 7.4,
              heatindex_f: 45.4,
              dewpoint_c: -2.5,
              dewpoint_f: 27.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 9.8,
              gust_kph: 15.7,
              uv: 0,
            },
            {
              time_epoch: 1759370400,
              time: '2025-10-02 04:00',
              temp_c: 7.5,
              temp_f: 45.5,
              is_day: 0,
              condition: {
                text: 'Felhős',
                icon: '//cdn.weatherapi.com/weather/64x64/night/119.png',
                code: 1006,
              },
              wind_mph: 6.9,
              wind_kph: 11.2,
              wind_degree: 32,
              wind_dir: 'NNE',
              pressure_mb: 1024,
              pressure_in: 30.25,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 45,
              cloud: 75,
              feelslike_c: 5.4,
              feelslike_f: 41.8,
              windchill_c: 5.4,
              windchill_f: 41.8,
              heatindex_c: 7.5,
              heatindex_f: 45.5,
              dewpoint_c: -3.7,
              dewpoint_f: 25.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 10.8,
              gust_kph: 17.4,
              uv: 0,
            },
            {
              time_epoch: 1759374000,
              time: '2025-10-02 05:00',
              temp_c: 7.5,
              temp_f: 45.5,
              is_day: 0,
              condition: {
                text: 'Felhős',
                icon: '//cdn.weatherapi.com/weather/64x64/night/119.png',
                code: 1006,
              },
              wind_mph: 7.4,
              wind_kph: 11.9,
              wind_degree: 37,
              wind_dir: 'NE',
              pressure_mb: 1024,
              pressure_in: 30.25,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 41,
              cloud: 64,
              feelslike_c: 5.3,
              feelslike_f: 41.6,
              windchill_c: 5.3,
              windchill_f: 41.6,
              heatindex_c: 7.5,
              heatindex_f: 45.5,
              dewpoint_c: -4.8,
              dewpoint_f: 23.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 11.2,
              gust_kph: 18,
              uv: 0,
            },
            {
              time_epoch: 1759377600,
              time: '2025-10-02 06:00',
              temp_c: 7.3,
              temp_f: 45.1,
              is_day: 0,
              condition: {
                text: 'Felhőtlen',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 8.5,
              wind_kph: 13.7,
              wind_degree: 37,
              wind_dir: 'NE',
              pressure_mb: 1025,
              pressure_in: 30.26,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 39,
              cloud: 14,
              feelslike_c: 4.7,
              feelslike_f: 40.5,
              windchill_c: 4.7,
              windchill_f: 40.5,
              heatindex_c: 7.3,
              heatindex_f: 45.1,
              dewpoint_c: -5.6,
              dewpoint_f: 22,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 12.8,
              gust_kph: 20.7,
              uv: 0,
            },
            {
              time_epoch: 1759381200,
              time: '2025-10-02 07:00',
              temp_c: 7.5,
              temp_f: 45.5,
              is_day: 1,
              condition: {
                text: 'Napos idő',
                icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                code: 1000,
              },
              wind_mph: 10.1,
              wind_kph: 16.2,
              wind_degree: 39,
              wind_dir: 'NE',
              pressure_mb: 1025,
              pressure_in: 30.27,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 39,
              cloud: 7,
              feelslike_c: 4.7,
              feelslike_f: 40.4,
              windchill_c: 4.7,
              windchill_f: 40.4,
              heatindex_c: 7.5,
              heatindex_f: 45.5,
              dewpoint_c: -5.6,
              dewpoint_f: 21.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.2,
              gust_kph: 22.9,
              uv: 0,
            },
            {
              time_epoch: 1759384800,
              time: '2025-10-02 08:00',
              temp_c: 8.6,
              temp_f: 47.5,
              is_day: 1,
              condition: {
                text: 'Napos idő',
                icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                code: 1000,
              },
              wind_mph: 13.6,
              wind_kph: 22,
              wind_degree: 37,
              wind_dir: 'NE',
              pressure_mb: 1025,
              pressure_in: 30.27,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 38,
              cloud: 12,
              feelslike_c: 5.5,
              feelslike_f: 41.8,
              windchill_c: 5.5,
              windchill_f: 41.8,
              heatindex_c: 8.6,
              heatindex_f: 47.5,
              dewpoint_c: -4.8,
              dewpoint_f: 23.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 17.1,
              gust_kph: 27.5,
              uv: 0.2,
            },
            {
              time_epoch: 1759388400,
              time: '2025-10-02 09:00',
              temp_c: 8.2,
              temp_f: 46.8,
              is_day: 1,
              condition: {
                text: 'Napos idő',
                icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                code: 1000,
              },
              wind_mph: 13.6,
              wind_kph: 22,
              wind_degree: 28,
              wind_dir: 'NNE',
              pressure_mb: 1024,
              pressure_in: 30.24,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 57,
              cloud: 0,
              feelslike_c: 6.7,
              feelslike_f: 44.1,
              windchill_c: 6.7,
              windchill_f: 44.1,
              heatindex_c: 9.6,
              heatindex_f: 49.4,
              dewpoint_c: -3.4,
              dewpoint_f: 25.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 15.7,
              gust_kph: 25.3,
              uv: 0.7,
            },
            {
              time_epoch: 1759392000,
              time: '2025-10-02 10:00',
              temp_c: 10.7,
              temp_f: 51.3,
              is_day: 1,
              condition: {
                text: 'Napos idő',
                icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                code: 1000,
              },
              wind_mph: 13.2,
              wind_kph: 21.2,
              wind_degree: 35,
              wind_dir: 'NE',
              pressure_mb: 1025,
              pressure_in: 30.27,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 38,
              cloud: 20,
              feelslike_c: 8.2,
              feelslike_f: 46.7,
              windchill_c: 8.2,
              windchill_f: 46.7,
              heatindex_c: 10.7,
              heatindex_f: 51.3,
              dewpoint_c: -2.9,
              dewpoint_f: 26.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 15.2,
              gust_kph: 24.4,
              uv: 1.5,
            },
            {
              time_epoch: 1759395600,
              time: '2025-10-02 11:00',
              temp_c: 11.7,
              temp_f: 53.1,
              is_day: 1,
              condition: {
                text: 'Részben felhős',
                icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                code: 1003,
              },
              wind_mph: 12.8,
              wind_kph: 20.5,
              wind_degree: 37,
              wind_dir: 'NE',
              pressure_mb: 1025,
              pressure_in: 30.26,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 37,
              cloud: 54,
              feelslike_c: 9.5,
              feelslike_f: 49.1,
              windchill_c: 9.5,
              windchill_f: 49.1,
              heatindex_c: 11.7,
              heatindex_f: 53.1,
              dewpoint_c: -2.6,
              dewpoint_f: 27.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.7,
              gust_kph: 23.6,
              uv: 2.4,
            },
            {
              time_epoch: 1759399200,
              time: '2025-10-02 12:00',
              temp_c: 12.5,
              temp_f: 54.6,
              is_day: 1,
              condition: {
                text: 'Borús',
                icon: '//cdn.weatherapi.com/weather/64x64/day/122.png',
                code: 1009,
              },
              wind_mph: 12.5,
              wind_kph: 20.2,
              wind_degree: 35,
              wind_dir: 'NE',
              pressure_mb: 1024,
              pressure_in: 30.24,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 34,
              cloud: 94,
              feelslike_c: 10.6,
              feelslike_f: 51,
              windchill_c: 10.6,
              windchill_f: 51,
              heatindex_c: 12.5,
              heatindex_f: 54.6,
              dewpoint_c: -2.7,
              dewpoint_f: 27.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.4,
              gust_kph: 23.2,
              uv: 3,
            },
            {
              time_epoch: 1759402800,
              time: '2025-10-02 13:00',
              temp_c: 13.1,
              temp_f: 55.5,
              is_day: 1,
              condition: {
                text: 'Részben felhős',
                icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                code: 1003,
              },
              wind_mph: 12.3,
              wind_kph: 19.8,
              wind_degree: 30,
              wind_dir: 'NNE',
              pressure_mb: 1023,
              pressure_in: 30.22,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 32,
              cloud: 44,
              feelslike_c: 11.2,
              feelslike_f: 52.2,
              windchill_c: 11.2,
              windchill_f: 52.2,
              heatindex_c: 13.1,
              heatindex_f: 55.5,
              dewpoint_c: -3.2,
              dewpoint_f: 26.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.2,
              gust_kph: 22.8,
              uv: 3.2,
            },
            {
              time_epoch: 1759406400,
              time: '2025-10-02 14:00',
              temp_c: 13.6,
              temp_f: 56.4,
              is_day: 1,
              condition: {
                text: 'Részben felhős',
                icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                code: 1003,
              },
              wind_mph: 12.3,
              wind_kph: 19.8,
              wind_degree: 32,
              wind_dir: 'NNE',
              pressure_mb: 1023,
              pressure_in: 30.21,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 30,
              cloud: 30,
              feelslike_c: 11.9,
              feelslike_f: 53.4,
              windchill_c: 11.9,
              windchill_f: 53.4,
              heatindex_c: 13.6,
              heatindex_f: 56.4,
              dewpoint_c: -3.5,
              dewpoint_f: 25.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.2,
              gust_kph: 22.8,
              uv: 2.6,
            },
            {
              time_epoch: 1759410000,
              time: '2025-10-02 15:00',
              temp_c: 13.5,
              temp_f: 56.4,
              is_day: 1,
              condition: {
                text: 'Napos idő',
                icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                code: 1000,
              },
              wind_mph: 12.5,
              wind_kph: 20.2,
              wind_degree: 35,
              wind_dir: 'NE',
              pressure_mb: 1023,
              pressure_in: 30.2,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 30,
              cloud: 25,
              feelslike_c: 11.8,
              feelslike_f: 53.3,
              windchill_c: 11.8,
              windchill_f: 53.3,
              heatindex_c: 13.6,
              heatindex_f: 56.4,
              dewpoint_c: -3.8,
              dewpoint_f: 25.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 15,
              gust_kph: 24.1,
              uv: 1.8,
            },
            {
              time_epoch: 1759413600,
              time: '2025-10-02 16:00',
              temp_c: 13.3,
              temp_f: 56,
              is_day: 1,
              condition: {
                text: 'Napos idő',
                icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                code: 1000,
              },
              wind_mph: 11.6,
              wind_kph: 18.7,
              wind_degree: 40,
              wind_dir: 'NE',
              pressure_mb: 1022,
              pressure_in: 30.19,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 30,
              cloud: 22,
              feelslike_c: 11.7,
              feelslike_f: 53,
              windchill_c: 11.7,
              windchill_f: 53,
              heatindex_c: 13.3,
              heatindex_f: 56,
              dewpoint_c: -4,
              dewpoint_f: 24.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.7,
              gust_kph: 23.7,
              uv: 0.9,
            },
            {
              time_epoch: 1759417200,
              time: '2025-10-02 17:00',
              temp_c: 12.3,
              temp_f: 54.2,
              is_day: 1,
              condition: {
                text: 'Napos idő',
                icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                code: 1000,
              },
              wind_mph: 9.4,
              wind_kph: 15.1,
              wind_degree: 52,
              wind_dir: 'NE',
              pressure_mb: 1023,
              pressure_in: 30.2,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 31,
              cloud: 16,
              feelslike_c: 10.8,
              feelslike_f: 51.4,
              windchill_c: 10.8,
              windchill_f: 51.4,
              heatindex_c: 12.3,
              heatindex_f: 54.2,
              dewpoint_c: -4.1,
              dewpoint_f: 24.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 13.4,
              gust_kph: 21.5,
              uv: 0.3,
            },
            {
              time_epoch: 1759420800,
              time: '2025-10-02 18:00',
              temp_c: 11.1,
              temp_f: 51.9,
              is_day: 1,
              condition: {
                text: 'Napos idő',
                icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                code: 1000,
              },
              wind_mph: 8.9,
              wind_kph: 14.4,
              wind_degree: 56,
              wind_dir: 'ENE',
              pressure_mb: 1023,
              pressure_in: 30.22,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 34,
              cloud: 16,
              feelslike_c: 9.3,
              feelslike_f: 48.7,
              windchill_c: 9.3,
              windchill_f: 48.7,
              heatindex_c: 11.1,
              heatindex_f: 51.9,
              dewpoint_c: -4.1,
              dewpoint_f: 24.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 13.5,
              gust_kph: 21.8,
              uv: 0,
            },
            {
              time_epoch: 1759424400,
              time: '2025-10-02 19:00',
              temp_c: 10.3,
              temp_f: 50.5,
              is_day: 0,
              condition: {
                text: 'Felhőtlen',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 9.6,
              wind_kph: 15.5,
              wind_degree: 48,
              wind_dir: 'NE',
              pressure_mb: 1024,
              pressure_in: 30.23,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 36,
              cloud: 12,
              feelslike_c: 8.2,
              feelslike_f: 46.7,
              windchill_c: 8.2,
              windchill_f: 46.7,
              heatindex_c: 10.3,
              heatindex_f: 50.5,
              dewpoint_c: -4,
              dewpoint_f: 24.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.6,
              gust_kph: 23.5,
              uv: 0,
            },
            {
              time_epoch: 1759428000,
              time: '2025-10-02 20:00',
              temp_c: 9.7,
              temp_f: 49.4,
              is_day: 0,
              condition: {
                text: 'Felhőtlen',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 9.4,
              wind_kph: 15.1,
              wind_degree: 45,
              wind_dir: 'NE',
              pressure_mb: 1024,
              pressure_in: 30.25,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 38,
              cloud: 8,
              feelslike_c: 7.5,
              feelslike_f: 45.5,
              windchill_c: 7.5,
              windchill_f: 45.5,
              heatindex_c: 9.7,
              heatindex_f: 49.4,
              dewpoint_c: -4,
              dewpoint_f: 24.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.1,
              gust_kph: 22.8,
              uv: 0,
            },
            {
              time_epoch: 1759431600,
              time: '2025-10-02 21:00',
              temp_c: 9.3,
              temp_f: 48.7,
              is_day: 0,
              condition: {
                text: 'Felhőtlen',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 9.4,
              wind_kph: 15.1,
              wind_degree: 45,
              wind_dir: 'NE',
              pressure_mb: 1024,
              pressure_in: 30.25,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 38,
              cloud: 14,
              feelslike_c: 7,
              feelslike_f: 44.6,
              windchill_c: 7,
              windchill_f: 44.6,
              heatindex_c: 9.3,
              heatindex_f: 48.7,
              dewpoint_c: -4.2,
              dewpoint_f: 24.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.1,
              gust_kph: 22.7,
              uv: 0,
            },
            {
              time_epoch: 1759435200,
              time: '2025-10-02 22:00',
              temp_c: 8.9,
              temp_f: 48,
              is_day: 0,
              condition: {
                text: 'Felhőtlen',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 9.6,
              wind_kph: 15.5,
              wind_degree: 42,
              wind_dir: 'NE',
              pressure_mb: 1024,
              pressure_in: 30.25,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 38,
              cloud: 9,
              feelslike_c: 6.5,
              feelslike_f: 43.7,
              windchill_c: 6.5,
              windchill_f: 43.7,
              heatindex_c: 8.9,
              heatindex_f: 48,
              dewpoint_c: -4.5,
              dewpoint_f: 23.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.7,
              gust_kph: 23.6,
              uv: 0,
            },
            {
              time_epoch: 1759438800,
              time: '2025-10-02 23:00',
              temp_c: 8.4,
              temp_f: 47.2,
              is_day: 0,
              condition: {
                text: 'Felhőtlen',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 9.8,
              wind_kph: 15.8,
              wind_degree: 35,
              wind_dir: 'NE',
              pressure_mb: 1024,
              pressure_in: 30.24,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 39,
              cloud: 7,
              feelslike_c: 5.9,
              feelslike_f: 42.6,
              windchill_c: 5.9,
              windchill_f: 42.6,
              heatindex_c: 8.4,
              heatindex_f: 47.2,
              dewpoint_c: -4.7,
              dewpoint_f: 23.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 15.2,
              gust_kph: 24.4,
              uv: 0,
            },
          ],
        },
      ],
    },
    alerts: {
      alert: [],
    },
  };
