import { HistoryWeatherResponse } from '@weather/contracts';

export const mockHistoryWeatherResponse: HistoryWeatherResponse = {
  location: {
    name: 'Budapest Ferenc Liszt International Airport',
    region: 'Budapest',
    country: 'Hungary',
    lat: 47.4297981262207,
    lon: 19.261100769043,
    tz_id: 'Europe/Budapest',
    localtime_epoch: 1759648776,
    localtime: '2025-10-05 09:19',
  },
  forecast: {
    forecastday: [
      {
        date: '2025-09-30',
        date_epoch: 1759190400,
        day: {
          maxtemp_c: 14.9,
          maxtemp_f: 58.8,
          mintemp_c: 10.2,
          mintemp_f: 50.4,
          avgtemp_c: 12.2,
          avgtemp_f: 53.9,
          maxwind_mph: 4.9,
          maxwind_kph: 7.9,
          totalprecip_mm: 0,
          totalprecip_in: 0,
          totalsnow_cm: 0,
          avgvis_km: 10,
          avgvis_miles: 6,
          avghumidity: 53,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: 'Patchy rain possible',
            icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
            code: 1063,
          },
          uv: 3,
        },
        astro: {
          sunrise: '06:40 AM',
          sunset: '06:24 PM',
          moonrise: '03:27 PM',
          moonset: '11:10 PM',
          moon_phase: 'First Quarter',
          moon_illumination: 49,
        },
        hour: [
          {
            time_epoch: 1759183200,
            time: '2025-09-30 00:00',
            temp_c: 10.9,
            temp_f: 51.6,
            is_day: 0,
            condition: {
              text: 'Patchy rain possible',
              icon: '//cdn.weatherapi.com/weather/64x64/night/176.png',
              code: 1063,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 80,
            wind_dir: 'E',
            pressure_mb: 1022,
            pressure_in: 30.19,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 65,
            cloud: 72,
            feelslike_c: 10.3,
            feelslike_f: 50.5,
            windchill_c: 10.3,
            windchill_f: 50.5,
            heatindex_c: 10.9,
            heatindex_f: 51.6,
            dewpoint_c: 4.7,
            dewpoint_f: 40.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.3,
            gust_kph: 10.1,
            uv: 0,
          },
          {
            time_epoch: 1759186800,
            time: '2025-09-30 01:00',
            temp_c: 10.7,
            temp_f: 51.3,
            is_day: 0,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
              code: 1003,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 85,
            wind_dir: 'E',
            pressure_mb: 1022,
            pressure_in: 30.19,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 64,
            cloud: 44,
            feelslike_c: 10.4,
            feelslike_f: 50.7,
            windchill_c: 10.4,
            windchill_f: 50.7,
            heatindex_c: 10.7,
            heatindex_f: 51.3,
            dewpoint_c: 4.1,
            dewpoint_f: 39.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.4,
            gust_kph: 8.6,
            uv: 0,
          },
          {
            time_epoch: 1759190400,
            time: '2025-09-30 02:00',
            temp_c: 10.4,
            temp_f: 50.7,
            is_day: 0,
            condition: {
              text: 'Patchy rain possible',
              icon: '//cdn.weatherapi.com/weather/64x64/night/176.png',
              code: 1063,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 88,
            wind_dir: 'E',
            pressure_mb: 1022,
            pressure_in: 30.19,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 63,
            cloud: 69,
            feelslike_c: 10.5,
            feelslike_f: 50.9,
            windchill_c: 10.5,
            windchill_f: 50.9,
            heatindex_c: 10.4,
            heatindex_f: 50.7,
            dewpoint_c: 3.7,
            dewpoint_f: 38.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4,
            gust_kph: 6.5,
            uv: 0,
          },
          {
            time_epoch: 1759194000,
            time: '2025-09-30 03:00',
            temp_c: 10.2,
            temp_f: 50.4,
            is_day: 0,
            condition: {
              text: 'Patchy rain possible',
              icon: '//cdn.weatherapi.com/weather/64x64/night/176.png',
              code: 1063,
            },
            wind_mph: 2,
            wind_kph: 3.2,
            wind_degree: 87,
            wind_dir: 'E',
            pressure_mb: 1022,
            pressure_in: 30.19,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 63,
            cloud: 100,
            feelslike_c: 10.7,
            feelslike_f: 51.3,
            windchill_c: 10.7,
            windchill_f: 51.3,
            heatindex_c: 10.2,
            heatindex_f: 50.4,
            dewpoint_c: 3.5,
            dewpoint_f: 38.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.1,
            gust_kph: 5,
            uv: 0,
          },
          {
            time_epoch: 1759197600,
            time: '2025-09-30 04:00',
            temp_c: 10.4,
            temp_f: 50.7,
            is_day: 0,
            condition: {
              text: 'Patchy rain possible',
              icon: '//cdn.weatherapi.com/weather/64x64/night/176.png',
              code: 1063,
            },
            wind_mph: 2,
            wind_kph: 3.2,
            wind_degree: 87,
            wind_dir: 'E',
            pressure_mb: 1022,
            pressure_in: 30.19,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 61,
            cloud: 100,
            feelslike_c: 10.8,
            feelslike_f: 51.4,
            windchill_c: 10.8,
            windchill_f: 51.4,
            heatindex_c: 10.4,
            heatindex_f: 50.7,
            dewpoint_c: 3.3,
            dewpoint_f: 37.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.1,
            gust_kph: 5,
            uv: 0,
          },
          {
            time_epoch: 1759201200,
            time: '2025-09-30 05:00',
            temp_c: 10.4,
            temp_f: 50.7,
            is_day: 0,
            condition: {
              text: 'Patchy rain possible',
              icon: '//cdn.weatherapi.com/weather/64x64/night/176.png',
              code: 1063,
            },
            wind_mph: 1.3,
            wind_kph: 2.2,
            wind_degree: 89,
            wind_dir: 'E',
            pressure_mb: 1023,
            pressure_in: 30.19,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 61,
            cloud: 100,
            feelslike_c: 10.4,
            feelslike_f: 50.7,
            windchill_c: 10.4,
            windchill_f: 50.7,
            heatindex_c: 10.4,
            heatindex_f: 50.7,
            dewpoint_c: 3.2,
            dewpoint_f: 37.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2,
            gust_kph: 3.2,
            uv: 0,
          },
          {
            time_epoch: 1759204800,
            time: '2025-09-30 06:00',
            temp_c: 10.7,
            temp_f: 51.3,
            is_day: 0,
            condition: {
              text: 'Patchy rain possible',
              icon: '//cdn.weatherapi.com/weather/64x64/night/176.png',
              code: 1063,
            },
            wind_mph: 0.7,
            wind_kph: 1.1,
            wind_degree: 138,
            wind_dir: 'SE',
            pressure_mb: 1023,
            pressure_in: 30.21,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 59,
            cloud: 89,
            feelslike_c: 10.7,
            feelslike_f: 51.3,
            windchill_c: 10.7,
            windchill_f: 51.3,
            heatindex_c: 10.7,
            heatindex_f: 51.3,
            dewpoint_c: 3.1,
            dewpoint_f: 37.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 0.9,
            gust_kph: 1.4,
            uv: 0,
          },
          {
            time_epoch: 1759208400,
            time: '2025-09-30 07:00',
            temp_c: 10.8,
            temp_f: 51.4,
            is_day: 1,
            condition: {
              text: 'Patchy rain possible',
              icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
              code: 1063,
            },
            wind_mph: 1.8,
            wind_kph: 2.9,
            wind_degree: 160,
            wind_dir: 'SSE',
            pressure_mb: 1023,
            pressure_in: 30.22,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 59,
            cloud: 92,
            feelslike_c: 10.8,
            feelslike_f: 51.4,
            windchill_c: 10.8,
            windchill_f: 51.4,
            heatindex_c: 10.8,
            heatindex_f: 51.4,
            dewpoint_c: 3.1,
            dewpoint_f: 37.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2.5,
            gust_kph: 4,
            uv: 0,
          },
          {
            time_epoch: 1759212000,
            time: '2025-09-30 08:00',
            temp_c: 11.1,
            temp_f: 52,
            is_day: 1,
            condition: {
              text: 'Cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/119.png',
              code: 1006,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 151,
            wind_dir: 'SSE',
            pressure_mb: 1024,
            pressure_in: 30.22,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 58,
            cloud: 82,
            feelslike_c: 11.2,
            feelslike_f: 52.2,
            windchill_c: 11.2,
            windchill_f: 52.2,
            heatindex_c: 11.1,
            heatindex_f: 52,
            dewpoint_c: 3.1,
            dewpoint_f: 37.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.6,
            gust_kph: 5.8,
            uv: 0,
          },
          {
            time_epoch: 1759215600,
            time: '2025-09-30 09:00',
            temp_c: 11.7,
            temp_f: 53.1,
            is_day: 1,
            condition: {
              text: 'Cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/119.png',
              code: 1006,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 142,
            wind_dir: 'SE',
            pressure_mb: 1024,
            pressure_in: 30.23,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 55,
            cloud: 87,
            feelslike_c: 11.9,
            feelslike_f: 53.4,
            windchill_c: 11.9,
            windchill_f: 53.4,
            heatindex_c: 11.7,
            heatindex_f: 53.1,
            dewpoint_c: 3,
            dewpoint_f: 37.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.4,
            gust_kph: 5.4,
            uv: 0,
          },
          {
            time_epoch: 1759219200,
            time: '2025-09-30 10:00',
            temp_c: 12.4,
            temp_f: 54.3,
            is_day: 1,
            condition: {
              text: 'Patchy rain possible',
              icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
              code: 1063,
            },
            wind_mph: 3.1,
            wind_kph: 5,
            wind_degree: 165,
            wind_dir: 'SSE',
            pressure_mb: 1024,
            pressure_in: 30.22,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 52,
            cloud: 74,
            feelslike_c: 12.4,
            feelslike_f: 54.3,
            windchill_c: 12.4,
            windchill_f: 54.3,
            heatindex_c: 12.4,
            heatindex_f: 54.3,
            dewpoint_c: 2.7,
            dewpoint_f: 36.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.6,
            gust_kph: 5.8,
            uv: 0.4,
          },
          {
            time_epoch: 1759222800,
            time: '2025-09-30 11:00',
            temp_c: 13.3,
            temp_f: 55.9,
            is_day: 1,
            condition: {
              text: 'Patchy rain possible',
              icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
              code: 1063,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 188,
            wind_dir: 'S',
            pressure_mb: 1023,
            pressure_in: 30.22,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 47,
            cloud: 86,
            feelslike_c: 13.6,
            feelslike_f: 56.5,
            windchill_c: 13.6,
            windchill_f: 56.5,
            heatindex_c: 13.3,
            heatindex_f: 55.9,
            dewpoint_c: 2.3,
            dewpoint_f: 36.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.1,
            gust_kph: 5,
            uv: 0.5,
          },
          {
            time_epoch: 1759226400,
            time: '2025-09-30 12:00',
            temp_c: 13.6,
            temp_f: 56.5,
            is_day: 1,
            condition: {
              text: 'Patchy rain possible',
              icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
              code: 1063,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 234,
            wind_dir: 'SW',
            pressure_mb: 1023,
            pressure_in: 30.21,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 46,
            cloud: 81,
            feelslike_c: 13.9,
            feelslike_f: 57,
            windchill_c: 13.9,
            windchill_f: 57,
            heatindex_c: 13.6,
            heatindex_f: 56.5,
            dewpoint_c: 2.1,
            dewpoint_f: 35.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.4,
            gust_kph: 5.4,
            uv: 0.9,
          },
          {
            time_epoch: 1759230000,
            time: '2025-09-30 13:00',
            temp_c: 14.1,
            temp_f: 57.4,
            is_day: 1,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 2.2,
            wind_kph: 3.6,
            wind_degree: 288,
            wind_dir: 'WNW',
            pressure_mb: 1023,
            pressure_in: 30.21,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 44,
            cloud: 39,
            feelslike_c: 14.8,
            feelslike_f: 58.6,
            windchill_c: 14.8,
            windchill_f: 58.6,
            heatindex_c: 14.1,
            heatindex_f: 57.4,
            dewpoint_c: 2,
            dewpoint_f: 35.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2.5,
            gust_kph: 4,
            uv: 2.9,
          },
          {
            time_epoch: 1759233600,
            time: '2025-09-30 14:00',
            temp_c: 14.9,
            temp_f: 58.8,
            is_day: 1,
            condition: {
              text: 'Cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/119.png',
              code: 1006,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 306,
            wind_dir: 'NW',
            pressure_mb: 1023,
            pressure_in: 30.2,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 41,
            cloud: 78,
            feelslike_c: 15.4,
            feelslike_f: 59.7,
            windchill_c: 15.4,
            windchill_f: 59.7,
            heatindex_c: 14.9,
            heatindex_f: 58.8,
            dewpoint_c: 1.8,
            dewpoint_f: 35.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.1,
            gust_kph: 5,
            uv: 0.7,
          },
          {
            time_epoch: 1759237200,
            time: '2025-09-30 15:00',
            temp_c: 14.9,
            temp_f: 58.8,
            is_day: 1,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 304,
            wind_dir: 'NW',
            pressure_mb: 1022,
            pressure_in: 30.19,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 40,
            cloud: 53,
            feelslike_c: 15.3,
            feelslike_f: 59.5,
            windchill_c: 15.3,
            windchill_f: 59.5,
            heatindex_c: 14.9,
            heatindex_f: 58.8,
            dewpoint_c: 1.2,
            dewpoint_f: 34.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.4,
            gust_kph: 5.4,
            uv: 0.8,
          },
          {
            time_epoch: 1759240800,
            time: '2025-09-30 16:00',
            temp_c: 14.7,
            temp_f: 58.5,
            is_day: 1,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 301,
            wind_dir: 'WNW',
            pressure_mb: 1022,
            pressure_in: 30.19,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 39,
            cloud: 36,
            feelslike_c: 15.3,
            feelslike_f: 59.5,
            windchill_c: 15.3,
            windchill_f: 59.5,
            heatindex_c: 14.7,
            heatindex_f: 58.5,
            dewpoint_c: 0.8,
            dewpoint_f: 33.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.4,
            gust_kph: 5.4,
            uv: 0.3,
          },
          {
            time_epoch: 1759244400,
            time: '2025-09-30 17:00',
            temp_c: 14.2,
            temp_f: 57.6,
            is_day: 1,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 320,
            wind_dir: 'NW',
            pressure_mb: 1023,
            pressure_in: 30.19,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 40,
            cloud: 30,
            feelslike_c: 14.7,
            feelslike_f: 58.5,
            windchill_c: 14.7,
            windchill_f: 58.5,
            heatindex_c: 14.2,
            heatindex_f: 57.6,
            dewpoint_c: 0.8,
            dewpoint_f: 33.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.8,
            gust_kph: 6.1,
            uv: 0,
          },
          {
            time_epoch: 1759248000,
            time: '2025-09-30 18:00',
            temp_c: 13.5,
            temp_f: 56.3,
            is_day: 1,
            condition: {
              text: 'Patchy rain possible',
              icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
              code: 1063,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 2,
            wind_dir: 'N',
            pressure_mb: 1023,
            pressure_in: 30.2,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 44,
            cloud: 80,
            feelslike_c: 13.7,
            feelslike_f: 56.7,
            windchill_c: 13.7,
            windchill_f: 56.7,
            heatindex_c: 13.6,
            heatindex_f: 56.5,
            dewpoint_c: 1.6,
            dewpoint_f: 34.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.9,
            gust_kph: 7.9,
            uv: 0,
          },
          {
            time_epoch: 1759251600,
            time: '2025-09-30 19:00',
            temp_c: 12.9,
            temp_f: 55.2,
            is_day: 0,
            condition: {
              text: 'Patchy rain possible',
              icon: '//cdn.weatherapi.com/weather/64x64/night/176.png',
              code: 1063,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 36,
            wind_dir: 'NE',
            pressure_mb: 1023,
            pressure_in: 30.22,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 49,
            cloud: 79,
            feelslike_c: 12.6,
            feelslike_f: 54.7,
            windchill_c: 12.6,
            windchill_f: 54.7,
            heatindex_c: 12.9,
            heatindex_f: 55.2,
            dewpoint_c: 2.6,
            dewpoint_f: 36.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.5,
            gust_kph: 10.4,
            uv: 0,
          },
          {
            time_epoch: 1759255200,
            time: '2025-09-30 20:00',
            temp_c: 12.3,
            temp_f: 54.1,
            is_day: 0,
            condition: {
              text: 'Patchy rain possible',
              icon: '//cdn.weatherapi.com/weather/64x64/night/176.png',
              code: 1063,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 57,
            wind_dir: 'ENE',
            pressure_mb: 1023,
            pressure_in: 30.22,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 54,
            cloud: 65,
            feelslike_c: 11.7,
            feelslike_f: 53.1,
            windchill_c: 11.7,
            windchill_f: 53.1,
            heatindex_c: 12.3,
            heatindex_f: 54.1,
            dewpoint_c: 3.3,
            dewpoint_f: 37.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.2,
            gust_kph: 11.5,
            uv: 0,
          },
          {
            time_epoch: 1759258800,
            time: '2025-09-30 21:00',
            temp_c: 11.7,
            temp_f: 53.1,
            is_day: 0,
            condition: {
              text: 'Patchy rain possible',
              icon: '//cdn.weatherapi.com/weather/64x64/night/176.png',
              code: 1063,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 66,
            wind_dir: 'ENE',
            pressure_mb: 1024,
            pressure_in: 30.23,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 58,
            cloud: 74,
            feelslike_c: 11.1,
            feelslike_f: 52,
            windchill_c: 11.1,
            windchill_f: 52,
            heatindex_c: 11.7,
            heatindex_f: 53.1,
            dewpoint_c: 3.6,
            dewpoint_f: 38.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.7,
            gust_kph: 10.8,
            uv: 0,
          },
          {
            time_epoch: 1759262400,
            time: '2025-09-30 22:00',
            temp_c: 11.2,
            temp_f: 52.2,
            is_day: 0,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
              code: 1003,
            },
            wind_mph: 3.1,
            wind_kph: 5,
            wind_degree: 68,
            wind_dir: 'ENE',
            pressure_mb: 1024,
            pressure_in: 30.23,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 59,
            cloud: 34,
            feelslike_c: 11.1,
            feelslike_f: 52,
            windchill_c: 11.1,
            windchill_f: 52,
            heatindex_c: 11.2,
            heatindex_f: 52.2,
            dewpoint_c: 3.5,
            dewpoint_f: 38.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.9,
            gust_kph: 7.9,
            uv: 0,
          },
          {
            time_epoch: 1759266000,
            time: '2025-09-30 23:00',
            temp_c: 10.9,
            temp_f: 51.6,
            is_day: 0,
            condition: {
              text: 'Cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/119.png',
              code: 1006,
            },
            wind_mph: 2.2,
            wind_kph: 3.6,
            wind_degree: 78,
            wind_dir: 'ENE',
            pressure_mb: 1024,
            pressure_in: 30.23,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 61,
            cloud: 80,
            feelslike_c: 11.2,
            feelslike_f: 52.2,
            windchill_c: 11.2,
            windchill_f: 52.2,
            heatindex_c: 10.9,
            heatindex_f: 51.6,
            dewpoint_c: 3.5,
            dewpoint_f: 38.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.6,
            gust_kph: 5.8,
            uv: 0,
          },
        ],
      },
    ],
  },
};
